In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [9]:
df=pd.read_csv("Dataset.csv")

##  1. Analyse exploratoire des données

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductId             2000 non-null   str
 1   ProductCategory       2000 non-null   str
 2   ChannelId             2000 non-null   str
 3   Amount                2000 non-null   float64
 4   Value                 2000 non-null   int64
 5   TransactionStartTime  2000 non-null   str
 6   PricingStrategy       2000 non-null   int64
 7   FraudResult           2000 non-null   int64
dtypes: float64(1), int64(3), str(4)
memory usage: 125.1 KB

##  transformation de la colonne TransactionStartTime en Date time.

In [16]:
df["TransactionStartTime"]=pd.to_datetime(df["TransactionStartTime"])
df["day"]=df["TransactionStartTime"].dt.day_name()
df["hour"]=df["TransactionStartTime"].dt.hour
df

,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,day,hour
0,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,Thursday,2
1,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,Thursday,2
2,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,Thursday,2
3,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,Thursday,3
4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,Thursday,3
...,...,...,...,...,...,...,...,...,...,...
1995,ProductId_14,financial_services,ChannelId_3,23400.0,23400,2018-11-28 05:13:37+00:00,2,0,Wednesday,5
1996,ProductId_3,airtime,ChannelId_3,1000.0,1000,2018-11-28 05:14:16+00:00,4,0,Wednesday,5
1997,ProductId_6,financial_services,ChannelId_2,-50.0,50,2018-11-28 05:15:30+00:00,2,0,Wednesday,5
1998,ProductId_1,airtime,ChannelId_3,1000.0,1000,2018-11-28 05:18:06+00:00,2,0,Wednesday,5
1999,ProductId_15,financial_services,ChannelId_3,1200.0,1200,2018-11-28 05:21:00+00:00,2,0,Wednesday,5

##  Visauliser les cinq premières observations

In [17]:
df.head(5)

,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,day,hour
0,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,Thursday,2
1,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,Thursday,2
2,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,Thursday,2
3,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,Thursday,3
4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,Thursday,3

##  Analyse descriptive

In [18]:
df.describe()

              Amount         Value  PricingStrategy  FraudResult         hour
count    2000.000000    2000.00000      2000.000000  2000.000000  2000.000000
mean     5913.507545    7154.24850         2.164500     0.003000    11.288000
std     45054.442262   44938.27784         0.673548     0.054704     3.925909
min    -60000.000000       8.00000         0.000000     0.000000     0.000000
25%       -50.000000     100.00000         2.000000     0.000000     9.000000
50%       900.000000    1000.00000         2.000000     0.000000    11.000000
75%      2000.000000    3500.00000         2.000000     0.000000    13.000000
max    800000.000000  800000.00000         4.000000     1.000000    23.000000

## visualiser le nombre de fraude

In [19]:
df.FraudResult.value_counts()

FraudResult
0    1994
1       6
Name: count, dtype: int64